package quiz2;

import java.awt.event.*;
import javax.swing.*;
import java.time.*;
import java.time.format.*;
import java.util.*;

public class BiodataForm extends javax.swing.JFrame {

    public BiodataForm() {
        initComponents();       
        
        lakiRadioButton.setActionCommand("Laki-Laki");
        perempuanRadioButton.setActionCommand("Perempuan");

        genderGroup.add(lakiRadioButton);
        genderGroup.add(perempuanRadioButton);    
        
        tgllahirText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                char c = evt.getKeyChar();
                String text = tgllahirText.getText();

                if (text.length() == 4 || text.length() == 7) {
                    if (c != '-') {
                        evt.consume(); 
                    }
                } else if (!Character.isDigit(c) && c != KeyEvent.VK_BACK_SPACE && c != KeyEvent.VK_DELETE) {
                    evt.consume();  
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderGroup = new javax.swing.ButtonGroup();
        namaText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lakiRadioButton = new javax.swing.JRadioButton();
        perempuanRadioButton = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamatField = new javax.swing.JTextArea();
        makanCheckBox = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        bermainCheckBox = new javax.swing.JCheckBox();
        tidurCheckBox = new javax.swing.JCheckBox();
        membacaCheckBox = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        telpText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pendidikanComboBox = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();
        tgllahirText = new javax.swing.JTextField();
        ipkText = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        nikText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        namaText.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        namaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaTextActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setText("Nama");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setText("Alamat");

        lakiRadioButton.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lakiRadioButton.setText("Laki-Laki");
        lakiRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lakiRadioButtonActionPerformed(evt);
            }
        });

        perempuanRadioButton.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        perempuanRadioButton.setText("Perempuan");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel4.setText("Jenis Kelamin");

        alamatField.setColumns(20);
        alamatField.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        alamatField.setRows(5);
        jScrollPane1.setViewportView(alamatField);

        makanCheckBox.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        makanCheckBox.setText("Makan");
        makanCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makanCheckBoxActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel5.setText("Hobi");

        bermainCheckBox.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        bermainCheckBox.setText("Bermain");

        tidurCheckBox.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tidurCheckBox.setText("Tidur");

        membacaCheckBox.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        membacaCheckBox.setText("Membaca");
        membacaCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                membacaCheckBoxActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel6.setText("No. Telp");

        telpText.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        telpText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telpTextActionPerformed(evt);
            }
        });
        telpText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telpTextKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel7.setText("Tanggal Lahir (YYYY-MM-DD)");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel8.setText("Pendidikan");

        pendidikanComboBox.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        pendidikanComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SD", "SMP", "SMA", "D1", "D2", "D3", "D4 / S1", "S2", "S3" }));
        pendidikanComboBox.setSelectedIndex(-1);
        pendidikanComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pendidikanComboBoxActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel9.setText("IPK");

        okButton.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        okButton.setText("Daftar");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        tgllahirText.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tgllahirText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tgllahirTextKeyReleased(evt);
            }
        });

        ipkText.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        ipkText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ipkTextKeyReleased(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel10.setText("NIK");

        nikText.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        nikText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nikTextActionPerformed(evt);
            }
        });
        nikText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nikTextKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Form Pendaftaran");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(namaText, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(makanCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lakiRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tidurCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(membacaCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(perempuanRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bermainCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(telpText)
                            .addComponent(pendidikanComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tgllahirText)
                            .addComponent(ipkText)
                            .addComponent(nikText, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)))
                    .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nikText)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(namaText)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lakiRadioButton)
                    .addComponent(perempuanRadioButton)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(makanCheckBox)
                            .addComponent(bermainCheckBox))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tidurCheckBox)
                            .addComponent(membacaCheckBox))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telpText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tgllahirText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pendidikanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ipkText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(okButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pendidikanComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pendidikanComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pendidikanComboBoxActionPerformed

    private void lakiRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lakiRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lakiRadioButtonActionPerformed

    private void membacaCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_membacaCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_membacaCheckBoxActionPerformed

    private void telpTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telpTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telpTextActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        StringBuilder sb = new StringBuilder();

        if (nikText.getText().isEmpty() || namaText.getText().isEmpty() || alamatField.getText().isEmpty() ||
            genderGroup.getSelection() == null || telpText.getText().isEmpty() || tgllahirText.getText().isEmpty() ||
            pendidikanComboBox.getSelectedItem() == null || ipkText.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua field wajib diisi!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return; 
        } 
        
       String pendidikan = pendidikanComboBox.getSelectedItem().toString();
       String[] pendidikanLevels = {"SD", "SMP", "SMA", "D1", "D2", "D3", "D4 / S1", "S2", "S3"};

       int pendidikanIndex = Arrays.asList(pendidikanLevels).indexOf(pendidikan);

       if (pendidikanIndex < 3) {
           JOptionPane.showMessageDialog(this, "Pendidikan minimal D1!", "Peringatan", JOptionPane.WARNING_MESSAGE);
           return; 
       }

        try {
            double ipk = Double.parseDouble(ipkText.getText());
            if (ipk < 3.01) {
                JOptionPane.showMessageDialog(this, "IPK minimal 3,01!", "Peringatan", JOptionPane.WARNING_MESSAGE);
                return; 
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "IPK harus berupa angka valid!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return; 
        }     
        
        sb.append("NIK: ").append(nikText.getText()).append("\n");
        sb.append("Nama: ").append(namaText.getText()).append("\n");
        sb.append("Alamat: ").append(alamatField.getText()).append("\n");

        ButtonModel genderModel = genderGroup.getSelection();
        sb.append("Gender: ").append(genderModel != null ? genderModel.getActionCommand() : "-").append("\n");

        if (!makanCheckBox.isSelected() && !tidurCheckBox.isSelected() && !bermainCheckBox.isSelected() && !membacaCheckBox.isSelected()) {
            JOptionPane.showMessageDialog(this, "Pilih minimal satu hobi!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return; 
        }        
        
        sb.append("Hobi: ");
        if (makanCheckBox.isSelected()) sb.append(makanCheckBox.getText()).append("\n");
        if (tidurCheckBox.isSelected()) sb.append(tidurCheckBox.getText()).append("\n");
        if (bermainCheckBox.isSelected()) sb.append(bermainCheckBox.getText()).append("\n");
        if (membacaCheckBox.isSelected()) sb.append(membacaCheckBox.getText()).append("\n");
       

        sb.append("No. Telp: ").append(telpText.getText()).append("\n");
        sb.append("Tanggal Lahir: ").append(tgllahirText.getText()).append("\n");
        
        Object pendidikanObject = pendidikanComboBox.getSelectedItem();
        sb.append("Pendidikan: ").append(pendidikanObject != null ? pendidikanObject : "-").append("\n");
        
        sb.append("IPK: ").append(ipkText.getText()).append("\n");
        
        JOptionPane.showMessageDialog(this, sb, "Biodata", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_okButtonActionPerformed

    private void makanCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makanCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_makanCheckBoxActionPerformed

    private void namaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaTextActionPerformed

    private void nikTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nikTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nikTextActionPerformed

    private void ipkTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ipkTextKeyReleased
        String ipk = ipkText.getText();

        if (ipk.length() > 4) {
            JOptionPane.showMessageDialog(null, "IPK tidak valid", "Peringatan", JOptionPane.WARNING_MESSAGE);
            ipkText.setText(""); 
            return;
        }

        try {
            double ipkValue = Double.parseDouble(ipk);

            if (ipkValue < 0.00 || ipkValue > 4.00) {
                JOptionPane.showMessageDialog(null, "IPK tidak valid", "Peringatan", JOptionPane.WARNING_MESSAGE);
                ipkText.setText(""); 
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "IPK tidak valid", "Peringatan", JOptionPane.WARNING_MESSAGE);
            ipkText.setText(""); 
        }
    }//GEN-LAST:event_ipkTextKeyReleased

    private void tgllahirTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tgllahirTextKeyReleased
        String tanggalLahir = tgllahirText.getText();

        if (tanggalLahir.length() == 10) {
            if (!tanggalLahir.matches("\\d{4}-\\d{2}-\\d{2}")) {
                JOptionPane.showMessageDialog(null, "Format tanggal tidak valid. Harap gunakan format YYYY-MM-DD", "Kesalahan", JOptionPane.ERROR_MESSAGE);
                tgllahirText.setText(""); 
                return; 
            }

            try {
                LocalDate birthDate = LocalDate.parse(tanggalLahir);
                LocalDate currentDate = LocalDate.now();

                int age = Period.between(birthDate, currentDate).getYears();

                if (age < 18) {
                    JOptionPane.showMessageDialog(null, "Anda belum cukup umur untuk melamar pekerjaan ini", "Peringatan", JOptionPane.WARNING_MESSAGE);
                    tgllahirText.setText(""); 
                }
            } catch (DateTimeParseException e) {
                JOptionPane.showMessageDialog(null, "Format tanggal tidak valid. Harap gunakan format YYYY-MM-DD", "Kesalahan", JOptionPane.ERROR_MESSAGE);
                tgllahirText.setText("");
            }
        }
    }//GEN-LAST:event_tgllahirTextKeyReleased

    private void telpTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telpTextKeyTyped
       char typedChar = evt.getKeyChar();

       if (!Character.isDigit(typedChar) && typedChar != '\b') {
           evt.consume(); 
       }
    }//GEN-LAST:event_telpTextKeyTyped

    private void nikTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nikTextKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c) && c != java.awt.event.KeyEvent.VK_BACK_SPACE) {
            evt.consume();
        }
    }//GEN-LAST:event_nikTextKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BiodataForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BiodataForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BiodataForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BiodataForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BiodataForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alamatField;
    private javax.swing.JCheckBox bermainCheckBox;
    private javax.swing.ButtonGroup genderGroup;
    private javax.swing.JTextField ipkText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton lakiRadioButton;
    private javax.swing.JCheckBox makanCheckBox;
    private javax.swing.JCheckBox membacaCheckBox;
    private javax.swing.JTextField namaText;
    private javax.swing.JTextField nikText;
    private javax.swing.JButton okButton;
    private javax.swing.JComboBox<String> pendidikanComboBox;
    private javax.swing.JRadioButton perempuanRadioButton;
    private javax.swing.JTextField telpText;
    private javax.swing.JTextField tgllahirText;
    private javax.swing.JCheckBox tidurCheckBox;
    // End of variables declaration//GEN-END:variables
}
